name: Subscribe a repo

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repo (only name, without org)'
        required: true
      base_branch:
        description: 'Branch to add workflow to'
        required: false
        default: 'master'

jobs:
  inject-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout py-launcher
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Clone target repo
        run: |
          git clone --depth=1 -b ${{ github.event.inputs.base_branch }} \
            https://x-access-token:${{ secrets.PY_LAUNCHER_PAT }}@github.com/Kiria-F/${{ github.event.inputs.target_repo }}.git \
            target-repo

      - name: Copy update-launcher workflow into target repo
        run: |
          mkdir -p target-repo/.github/workflows
          cp .workflow-templates/update-launcher.yml target-repo/.github/workflows/update-launcher.yml

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PY_LAUNCHER_PAT }}
        run: |
          BRANCH="add-launcher-sync-$(date +%s)"
          gh pr create \
            --title "Subscribe to launcher updates" \
            --body "This adds a workflow that keeps launcher.py in sync with py-launcher." \
            --base "${{ github.event.inputs.base_branch }}" \
            --head "$BRANCH" \
            --repo "Kiria-F/${{ github.event.inputs.target_repo }}"


      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PY_LAUNCHER_PAT }}
        run: |
          gh pr create \
            --title "Subscribe to launcher updates" \
            --body "This adds a workflow that keeps launcher.py in sync with py-launcher." \
            --base ${{ github.event.inputs.base_branch }} \
            --head $BRANCH \
            --repo Kiria-F/${{ github.event.inputs.target_repo }}
